repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120", "--src-path", "dexmani_real"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: conda run -n real_robot mypy dexmani_real/
        language: system
        types: [python]
        pass_filenames: false
